# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Show versions
        run: |
          python -V
          pip -V

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          # инструменты для CI отдельно, чтобы не зависеть от requirements.txt
          pip install black isort flake8 pytest

      - name: Lint with black
        run: |
          black --version
          black --check src tests || (echo "Black failed"; exit 1)

      - name: Lint imports with isort
        run: |
          isort --version
          isort --check-only src tests || (echo "isort failed"; exit 1)

      - name: Lint with flake8
        run: |
          flake8 --version
          # NB: явно укажем директории, которые точно существуют
          flake8 src tests || (echo "flake8 failed"; exit 1)

      - name: Run tests (pytest)
        run: |
          pytest -q || (echo "pytest failed"; exit 1)
